paths:
  static: public
  uploads: public/uploads
timezone: America/New_York
markdown:
  engine: commonmark
  options:
    gfm: true
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
  source:
    path: ''
    icon: package_2
  bikes:
    path: src/content/bikes
    icon: files
